name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' 

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --debug --base-href="/my-flutter-framework/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
